# Generated by Django 5.1.6 on 2025-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_shortenedurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_link',
            field=models.CharField(default='gVVele', max_length=20, unique=True),
        ),
    ]
