# Generated by Django 5.1.6 on 2025-02-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_shortenedurl_short_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='original_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_link',
            field=models.CharField(default='eiVPyL', max_length=20, unique=True),
        ),
    ]
