# Generated by Django 5.1.6 on 2025-02-11 07:06

import hello.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_shortenedurl_original_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenedurl',
            name='short_link',
            field=models.CharField(default=hello.models.generate_short_link, max_length=20, unique=True),
        ),
    ]
