# Generated by Django 5.1.5 on 2025-02-11 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_shortenedurl_short_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
